# Generated by Django 4.0.5 on 2022-06-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FyersStockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fytoken', models.IntegerField()),
                ('SymbolDetails', models.CharField(max_length=50)),
                ('ExchangeInstrumentType', models.IntegerField(blank=True)),
                ('MinimumLotSize', models.IntegerField(blank=True)),
                ('TickSize', models.FloatField(blank=True)),
                ('ISIN', models.CharField(blank=True, max_length=100)),
                ('TradingSession', models.CharField(blank=True, max_length=50)),
                ('LastUpdateDate', models.CharField(blank=True, max_length=50)),
                ('ExpiryDate', models.CharField(blank=True, max_length=50)),
                ('SymbolTicker', models.CharField(blank=True, max_length=100)),
                ('Exchange', models.IntegerField(blank=True)),
                ('Segment', models.IntegerField(blank=True)),
                ('ScripCode', models.IntegerField(blank=True)),
                ('MainStockName', models.CharField(blank=True, max_length=100)),
                ('UnderlyingScripCode', models.IntegerField(blank=True)),
                ('StrikePrice', models.FloatField(blank=True)),
                ('OptionType', models.CharField(blank=True, max_length=50)),
                ('date_added', models.DateTimeField(blank=True)),
                ('date_updated', models.DateTimeField(blank=True)),
            ],
        ),
    ]
