# Generated by Django 4.0.5 on 2022-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyersstocklist',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fyersstocklist',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
