# Generated by Django 4.0.5 on 2022-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_fyersstocklist_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FyersStockDepthTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('fyCode', models.IntegerField(blank=True)),
                ('ltp', models.FloatField(blank=True)),
                ('price', models.FloatField(blank=True)),
                ('qty', models.IntegerField(blank=True)),
                ('num_orders', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FyersStockTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.IntegerField(blank=True)),
                ('fyCode', models.IntegerField(blank=True)),
                ('fyFlag', models.IntegerField(blank=True)),
                ('pktLen', models.IntegerField(blank=True)),
                ('ltp', models.FloatField(blank=True)),
                ('open_price', models.FloatField(blank=True)),
                ('high_price', models.FloatField(blank=True)),
                ('low_price', models.FloatField(blank=True)),
                ('close_price', models.FloatField(blank=True)),
                ('min_open_price', models.FloatField(blank=True)),
                ('min_high_price', models.FloatField(blank=True)),
                ('min_low_price', models.FloatField(blank=True)),
                ('min_close_price', models.FloatField(blank=True)),
                ('min_volume', models.IntegerField(blank=True)),
                ('last_traded_qty', models.IntegerField(blank=True)),
                ('last_traded_time', models.IntegerField(blank=True)),
                ('avg_trade_price', models.FloatField(blank=True)),
                ('vol_traded_today', models.IntegerField(blank=True)),
                ('tot_buy_qty', models.IntegerField(blank=True)),
                ('tot_sell_qty', models.IntegerField(blank=True)),
            ],
        ),
    ]
