from django.db import models
import datetime

class FyersStockList(models.Model):
    Fytoken = models.IntegerField()
    SymbolDetails = models.CharField(max_length=50)
    ExchangeInstrumentType = models.IntegerField(blank=True)
    MinimumLotSize = models.IntegerField(blank=True)
    TickSize = models.FloatField(blank=True)
    ISIN = models.CharField(max_length=100,blank=True)
    TradingSession = models.CharField(max_length=50,blank=True)
    LastUpdateDate = models.CharField(max_length=50,blank=True)
    ExpiryDate=models.CharField(max_length=50,blank=True)
    SymbolTicker = models.CharField(max_length=100,blank=True)
    Exchange = models.IntegerField(blank=True)
    Segment = models.IntegerField(blank=True)
    ScripCode = models.IntegerField(blank=True)
    MainStockName = models.CharField(max_length=100, blank=True)
    UnderlyingScripCode = models.IntegerField(blank=True)
    StrikePrice = models.FloatField(blank=True)
    OptionType = models.CharField(max_length=50, blank=True)
    date_added = models.DateTimeField(blank=True, null=True)
    date_updated = models.DateTimeField(blank=True, null=True)

class FyersStockTracker(models.Model):
    symbol = models.CharField(max_length=50, blank=True)
    timestamp = models.IntegerField(blank=True)
    fyCode = models.IntegerField(blank=True)
    fyFlag = models.IntegerField(blank=True)
    pktLen = models.IntegerField(blank=True)
    ltp = models.FloatField(blank=True)
    open_price = models.FloatField(blank=True)
    high_price = models.FloatField(blank=True)
    low_price = models.FloatField(blank=True)
    close_price = models.FloatField(blank=True)
    min_open_price = models.FloatField(blank=True)
    min_high_price = models.FloatField(blank=True)
    min_low_price = models.FloatField(blank=True)
    min_close_price = models.FloatField(blank=True)
    min_volume = models.IntegerField(blank=True)
    last_traded_qty = models.IntegerField(blank=True)
    last_traded_time = models.IntegerField(blank=True)
    avg_trade_price = models.FloatField(blank=True)
    vol_traded_today = models.IntegerField(blank=True)
    tot_buy_qty = models.IntegerField(blank=True)
    tot_sell_qty = models.IntegerField(blank=True)
    date_added = models.DateTimeField(blank=True, null=True)

class FyersStockDepthTracker(models.Model):
    symbol = models.CharField(max_length=50, blank=True)
    fyCode = models.IntegerField(blank=True)
    timestamp = models.IntegerField(blank=True)
    ltp = models.FloatField(blank=True)
    price = models.FloatField(blank=True)
    qty = models.IntegerField(blank=True)
    num_orders = models.IntegerField(blank=True)
    date_added = models.DateTimeField(blank=True, null=True)

class FyersStrategyStraddleTracker(models.Model):
    strategy_name = models.CharField(max_length=50, blank=True)
    strategy_id = models.CharField(max_length=50, blank=True)
    track_symbol = models.CharField(max_length=50, blank=True)
    track_level = models.CharField(max_length=50, blank=True)
    track_direction = models.CharField(max_length=50, blank=True) #UP or Down
    track_ltp = models.FloatField(blank=True)
    track_ltp_updatedt = models.DateTimeField(blank=True, null=True)
    istargetreached = models.FloatField(blank=True)
    target_symbol = models.CharField(max_length=50, blank=True)
    target_level = models.FloatField(blank=True)
    quantity = models.IntegerField(blank=True, null=True)
    date_added = models.DateTimeField(blank=True, null=True)

class FyersStrategyStrangleTracker(models.Model):
    strategy_name = models.CharField(max_length=50, blank=True)
    strategy_id = models.CharField(max_length=50, blank=True)
    track_symbol = models.CharField(max_length=50, blank=True)
    track_level = models.CharField(max_length=50, blank=True)
    track_direction = models.CharField(max_length=50, blank=True) #UP or Down
    track_ltp = models.FloatField(blank=True)
    track_ltp_updatedt = models.DateTimeField(blank=True, null=True)
    istargetreached = models.FloatField(blank=True)
    target_symbol_ce = models.CharField(max_length=50, blank=True)
    target_symbol_pe = models.CharField(max_length=50, blank=True)
    quantity = models.IntegerField(blank=True, null=True)
    target_level = models.FloatField(blank=True)
    date_added = models.DateTimeField(blank=True, null=True)